packages:
  - playground

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver

onlyBuiltDependencies:
  - simple-git-hooks


overrides:
  "@nuxt/schema": "4.4.2"
  "@nuxtjs/critters": "link:./"
