packages:
  - playground

overrides:
  "@nuxt/schema": "4.5.1"
  "@nuxtjs/critters": "link:./"

allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  simple-git-hooks: true
  unrs-resolver: false
